### ISSUE TITLE
const Octokit is deprecated

### ISSUE THREAD

**Issue by mauriciofauth** [dessant/lock-threads#17] opened 2020-06-21 16:18 UTC
https://github.com/phpmyadmin/phpmyadmin/runs/793102151?check_suite_focus=true

```
Run dessant/lock-threads@v2
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
```

**Comment by netniV** [comment] 2020-06-30 10:42
This issue is actually caused by the GitHub Toolkit action, see https://github.com/actions/toolkit/issues/333 and was resolved in release 2.1.1 (See https://github.com/actions/toolkit/blob/master/packages/github/RELEASES.md).

I've created a PR for it https://github.com/dessant/lock-threads/pull/18

**Closed** 2020-07-07 20:34 UTC
